name: C++ CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Verify GCC installation
        run: g++ --version

      - name: Build the C++ file
        run: |
          g++ hello.cpp -o hello
          if [ $? -eq 0 ]; then  # Check if g++ was successful
            ./hello
          else
            echo "Build failed: hello.cpp didn't compile."
            exit 1  # Exit the pipeline with a failure status
          fi

      - name: Display the output
        run: |
          if [ -f hello ]; then
            ./hello
          else
            echo "Build failed: hello.cpp didn't compile."
          fi
